string:
  profiles:
    active:
      - dev
---
string:
  profiles: dev ##开发环境 
  application: 
    name: microservicecloud-dev
---
string:
  profiles: test  #测试环境
  application: 
    name: microservicelou-test